#:schema https://raw.githubusercontent.com/release-plz/release-plz/refs/heads/main/.schema/latest.jsonc
[[package]]
changelog_path = "CHANGELOG.md"
name = "arachne"

[changelog]
header = """<!-- markdownlint-disable MD024 -->

# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
and adheres to [Semantic Versioning](https://semver.org/).

## [Unreleased]
"""
